### ISSUE TITLE
Disable bluetooth-audio service by setting a variable

### ISSUE THREAD

**Issue by densmtl** [balenalabs/balena-sound#196]
**Description**
I have BalenaSound running on an RPi 2 that does not have bluetooth, When I restart the device, the bluetooth-audio service keeps failing to start and loops. I have to stop it manually via the web portal every time.

**Potential Solution**
Implement a way to prevent the service from starting by setting a variable (like the variable DISABLE_MULTI_ROOM to prevent the fleet-supervisor and the rest from starting)

**Alternatives considered**
* Change the restart directive in docker-compose.yml from always to never. 
* Comment out the entire bluetooth-audio stanza in docker-compose.yml.

**Comment by VincentChalnot** [comment]
I'll also be interested by this feature as the bluetooth seems to impact on spotify performances.

**Comment by zaggash** [comment]
Or you can remove the Bluetooth part from the docker-compose.
Just remove :
```
bluetooth-audio:
    build: ./bluetooth-audio
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
      - snapcast:/var/cache/snapcast
```
and delete the folder `bluetooth-audio/`

The push a new version of your app :)
